### ISSUE TITLE
Not able to commit.

### ISSUE THREAD

**Issue by pmas1998** [githubteacher/fluffy-lamp#10]
Please slow down!!!

**Comment by katalysttech** [comment]
Acccess denied to repository

**Comment by patrickmckenna** [comment]
@pmas1998 Are you able to commit now?

@katalysttech Are you still getting denied? You are a collaborator, and do have write access.

**Comment by pmas1998** [comment]
I am able to commit. But the instructor is going waaaayyy too fast and we are not able to follow all the commands. She doesn't wait even for a second. This seems like a lecture and not hands on training. Sorry, just my view. It is a little frustrating.

**Comment by patrickmckenna** [comment]
@pmas1998 No need to apologize, we really appreciate the candor. Pacing can be tricky, and we try to accommodate the majority, but that of course doesn't work for everyone. Right now, a solid majority of the class has said the pace is "about right."

Please see [this doc](https://github.com/githubteacher/fluffy-lamp/blob/master/basic-workflow.md) for an overview of the commands we used locally.

**Comment by patrickmckenna** [comment]
@pmas1998 And please keep asking questions, we'll try our best to clear things up!
