### ISSUE TITLE
I pushed but I don't see it in the repo

### ISSUE THREAD

**Issue by dcondol** [githubteacher/fluffy-lamp#40]

**Comment by patrickmckenna** [comment]
@dcondol What was the output of `git push -u origin <your-branch-name>`?

**Comment by dcondol** [comment]
'Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 334 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)

**Comment by tallus** [comment]
it's here: https://github.com/githubteacher/fluffy-lamp/tree/dcondol-places

**Comment by patrickmckenna** [comment]
@dcondol You did everything correctly. Thanks @tallus!
