### ISSUE TITLE
Unable to collaborate

### ISSUE THREAD

**Issue by AlanKnutson** [githubteacher/fluffy-lamp#49]
Not in drop down 'compare-master' of pull request

**Comment by patrickmckenna** [comment]
@AlanKnutson Are you saying that you don't see your branch on `github.com`?

**Comment by AlanKnutson** [comment]
yes exactly

**Comment by patrickmckenna** [comment]
@AlanKnutson Were you able to create a branch locally? If so, what did you call it? Did you do `git push -u origin <your-branch-name>`?

**Comment by AlanKnutson** [comment]
Unfortunately I am unable because of our firewall

**Comment by patrickmckenna** [comment]
@AlanKnutson Ah, that can be a tricky, sorry. Have you tried using https instead of ssh?

**Comment by AlanKnutson** [comment]
Ill try that - thank you!
