### ISSUE TITLE
problem branching

### ISSUE THREAD

**Issue by cchay** [githubteacher/fluffy-lamp#5]
I created a local branch and push.  
I get a warning: Permanently added the rsa host key for ip address 192.30.252.128
I get "everything up-to-date".  But the branch is not pushed.  How come?

**Comment by patrickmckenna** [comment]
@cchay You probably got the warning because you're using SSH to authenticate. For the moment, though, don't worry about 'git push` -- we'll get to that shortly.

**Comment by cchay** [comment]
I had this problem YESTERDAY.  :)
I tried to create a branch that I can use, but I am unable to.  Can you create a branch for me to use?  Call it "cchay_remote"?

**Comment by patrickmckenna** [comment]
@cchay Sorry, having some trouble understanding where the problem is occurring. You are unable to create a branch locally, after cloning the repo and cd'ing into it?

**Comment by cchay** [comment]
I can create the branch locally.  I am unable to PUSH the branch to the github.com repository.

**Comment by cchay** [comment]
I am added as a collaborator.  I do not get any errors.

**Comment by cchay** [comment]
it works now, for some reason.
