### ISSUE TITLE
Instructor

### ISSUE THREAD

**Issue by pmas1998** [githubteacher/fluffy-lamp#55]
I'm figuring that there is a lot to get through but you are going waaaaayyyy too fast. May be better to reduce the amount of content to get through. I don't think we are learning very much.

**Comment by patrickmckenna** [comment]
@pmas1998 Please see my comments [here](https://github.com/githubteacher/fluffy-lamp/issues/10#issuecomment-126753181). Also, we are recording this, and you'll get a link to the video next week. Hope that helps.
