### ISSUE TITLE
Please show the git diff diagram 1 more time

### ISSUE THREAD

**Issue by wbgannon** [githubteacher/fluffy-lamp#59]

**Comment by patrickmckenna** [comment]
@wbgannon What did you mean by diagram?

**Comment by wbgannon** [comment]
the presenter showed a slide with 
get diff 
get diff staged
get diff HEAD

**Comment by patrickmckenna** [comment]
@wbgannon Ah, got it. This one, right?

![diff-options](https://cloud.githubusercontent.com/assets/3589536/9013263/af12455c-376f-11e5-8d72-63824dd11a99.jpg)
