### ISSUE TITLE
what if you want to get the clean copy from master not merge from branch

### ISSUE THREAD

**Issue by rgarapat** [githubteacher/fluffy-lamp#68]

**Comment by patrickmckenna** [comment]
@rgarapat Sorry, trying to understand the question. What scenario are you imagining? Why merge if you want to keep the version of the file you already have?

**Comment by rgarapat** [comment]
I started to merge but when i saw conflicts and couldn't resolve completely in case of large file, I want to come back to the original master copy rather than the branch one.

**Comment by patrickmckenna** [comment]
@rgarapat Did that answer your question?

**Comment by tallus** [comment]
git checkout --theirs:  use changes from branch being merged
git checkout --ours: keep file as it exists in our branch (branch being merged intro)

**Comment by patrickmckenna** [comment]
@rgarapat Yup, @tallus points out another useful method. (Thanks, @tallus!) Note though that `git checkout` is not working directory safe -- it will overwrite whatever currently exists there. 

There are many other options still, and we cover a few more of them in that video.
