### ISSUE TITLE
git showing up in files - what did I do wrong?

### ISSUE THREAD

**Issue by Kevin-C-Bell** [githubteacher/fluffy-lamp#70]
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	git
	three.md

**Comment by patrickmckenna** [comment]
@Kevin-C-Bell It looks like you created a file or folder called `git`. The `.git` (note the dot) folder is actually where Git stores all of its data.

**Comment by Kevin-C-Bell** [comment]
It is a zero byte file in my file system, but I did not create it. Strange.
