### ISSUE TITLE
XCODE gitigore?

### ISSUE THREAD

**Issue by Kevin-C-Bell** [githubteacher/fluffy-lamp#87]
I see there are options for both swift and Obj-c, but these can be mixed in one project. Is there a way to combine these two for Xcode?

**Comment by Kevin-C-Bell** [comment]
@patrickmckenna @crichID

**Comment by patrickmckenna** [comment]
@Kevin-C-Bell Yup. `.gitignore` is just a plaintext file that lives at the root level of your project. So just copy/paste as needed. 

The templates we showed are just that; you're definitely encouraged to amend them in individual projects. Feel free to submit a pull request, too! The templates come from [this open-source repo](https://github.com/github/gitignore).

**Comment by Kevin-C-Bell** [comment]
Cool! Thanks for getting back to me.
