### ISSUE TITLE
Am not able to git commit 

### ISSUE THREAD

**Issue by deanme18** [githubteacher/fluffy-lamp#9]
I'm on Windows and when I do the command:
git commit -m"starting staugustine fl file"
it just comes back with a ">>" prompt

**Comment by deanme18** [comment]
I have tried both using a single quote (') and a double-quote (") and the same thing happens.  The same prompt comes back.  (>>)

**Comment by patrickmckenna** [comment]
@deanme18 Was @crichID's explanation just now sufficient, or still running into trouble?

**Comment by patrickmckenna** [comment]
@deanme18 If that happens, you can type `ctrl-c` to cancel the current command.

**Comment by deanme18** [comment]
I did, but when doing a git status the file still shows as a "new" file.

**Comment by patrickmckenna** [comment]
@deanme18 Ah, did you type `git add <your-filename-here>`?

**Comment by deanme18** [comment]
Yes

**Comment by patrickmckenna** [comment]
@deanme18 When you type `git status`, do you see a message like this?

```
On branch <your-branch>
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   <your-file>
```

**Comment by patrickmckenna** [comment]
@deanme18 If so, you can also try typing `git commit` without the `-m` flag, and Git will open your default text editor. You can type a commit message there, save and close the window, and that should do the trick.
